### ISSUE TITLE
When I run the A_star ,there is an error

### ISSUE THREAD

**Issue by jiao-post** [Mesywang/Motion-Planning-Algorithm#1]
Function or variable 'insert_open' is not recognized
ERROR A_star_search (line 67)
    OPEN(OPEN_COUNT,:)=insert_open(xNode,yNode,xNode,yNode,goal_distance,path_cost,goal_distance);  %默认OPEN list
    中1/0为1，表示未被访问

**Comment by Mesywang** [comment]
Because the function "insert_open" is in the subfolder, you should add the current folder and its subfolders to matlab's search path.

**Comment by jiao-post** [comment]
Thank you for helping me solve this problem

**Comment by jiao-post** [comment]
Thank you ！！！
